theme_inspector_entity.theme_inspector_entity_preview.*:
  type: config_entity
  label: Entity Preview
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    entity_type_id:
      type: string
    entity_uuid:
      type: string
